
gcc7: smartptr.cpp
	g++-8 -Wall -Wpedantic -Wextra -Wno-unused -std=gnu++17 -g -ggdb $^ -o smartptr

clang4: smartptr.cpp
	clang++ -Wall -Wpedantic -Wextra -Wno-unused -Wno-unused-parameter -std=c++1z -g -ggdb $^ -o smartptr

gcc6: smartptr.cpp
	g++ -Wall -Wpedantic -Wextra -Wno-unused -std=gnu++17 -g -ggdb $^ -o smartptr

clang3: smartptr.cpp
	clang++ -Wall -Wpedantic -Wextra -Wno-unused -Wno-unused-parameter -std=c++1z -g -ggdb $^ -o smartptr
