
smartptr: smartptr.cpp
	g++ -Wall -Wpedantic -Wextra -Wno-unused -std=c++17 -g -ggdb $^ -o smartptr
	clang++ -Wall -Wpedantic -Wextra -Wno-unused -Wno-unused-parameter -std=c++1z -g -ggdb $^ -o smartptr
